accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

from .views import LoginFormView, UserRegistrationView, ProfileUpdateView

urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    
    # change password
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    
    # profile
    path('profile/', ProfileUpdateView.as_view(), name='profile_url')
    
    
    
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail_url'),
    path('add/<int:product_id>/', CartAddProductFormView.as_view(), name='cart_add_url'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove_url')
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    
    # Local apps
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('listings.urls', namespace='listings')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required

from .views import *
from decorators import user_created_order

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateViewForm.as_view(), name='order_create_url'),
    path('admin/order/<int:order_id>/pdf/', staff_member_required(invoice_pdf), name='invoice_pdf_url'),
    path('order/<int:order_id>/pdf/', user_created_order(customer_invoice_pdf), name='customer_invoice_pdf'),
    path('order/<int:order_id>/', OrderDetailView.as_view(), name='order_detail_url')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.conf import settings


class CustomUserManager(UserManager):
    
    def get_user_by_email(self, email):
        user = None
        try:
            user = self.get(email=email)
        except CustomUser.DoesNotExist:
            pass
        return user
    

class CustomUser(AbstractUser):
    objects = CustomUserManager()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=250, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return f"{self.user.username} profile"
    
    

accounts/forms.py
from django import forms
from django.core.validators import validate_email
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

from .models import Profile


class LoginForm(forms.Form):
    email = forms.CharField(required=True, validators=[validate_email], widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))


class UserRegistrationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': ('The two password fields didn’t match.'),}
    
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    email = forms.CharField(required=True, validators=[validate_email], widget=forms.EmailInput(attrs={
        'class': 'form-control'}))

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',)
        return password2
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        try:
            validate_password(password, user=self.instance)
        except ValidationError as errors:
            raise ValidationError(errors)
        return password
        
    
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'password')
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': True}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'required': True}),
            'password': forms.PasswordInput(
                attrs={'class': 'form-control'})}
        

class UpdateUserForm(forms.ModelForm):
    
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'fprm-control'}),
            'last_name': forms.TextInput(attrs={'class': 'from-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'})
        }
        

class UpdateProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ('phone_number', 'address', 'postal_code', 'city', 'country')
        widgets = {
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'control-form'}),
            'country': forms.TextInput(attrs={'class': 'form-control'})
        }

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user_model, get_user
from django.contrib import messages
from django.conf import settings

from .forms import (LoginForm, UserRegistrationForm, 
                    UpdateUserForm, UpdateProfileForm)
from .models import Profile

CustomUser = get_user_model()


class LoginFormView(View):
    template_name = 'accounts/login.html',
        
    def get(self, request, *args, **kwargs):
        login_form = LoginForm()
        return render(request, self.template_name, {'form': login_form})

    def post(self, request, *args, **kwargs):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            return self.form_valid(login_form)
        return self.form_invalid(login_form)

    def form_invalid(self, login_form):
        return render(self.request, self.template_name, {'form': login_form})

    def form_valid(self, login_form):
        data = login_form.cleaned_data
        user_record = CustomUser.objects.get_user_by_email(email=data['email'])
        if user_record:
            user = authenticate(self.request, username=user_record, password=data['password'])
            if user:
                login(self.request, user)
                messages.success(self.request, 'You have logged in successfully')
                return redirect(settings.LOGIN_REDIRECT_URL)
        messages.error(self.request, 'Incorrect email / password')
        return render(self.request, self.template_name, {'form': login_form})


class UserRegistrationView(View):
    template_name = 'accounts/register.html'
    successful_template_name = 'accounts/register_done.html'

    def post(self, request, *args, **kwargs):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            return self.form_valid(user_form)
        return self.form_invalid(user_form)

    def get(self, request, *args, **kwargs):
        user_form = UserRegistrationForm()
        return render(request, self.template_name, {'user_form': user_form})

    def form_invalid(self, user_form):
        return render(self.request, self.template_name, {'user_form': user_form})

    def form_valid(self, user_form):
        data = user_form.cleaned_data

        email = data['email']
        password = data['password']
        password2 = data['password2']

        if CustomUser.objects.filter(email=email).exists():
            messages.error(self.request, 'User with given email alredy exists')
            return render(self.request, self.template_name, {'user_form': user_form})
        
        # Create new user object
        new_user = CustomUser.objects.create_user(
            first_name=data['first_name'],
            last_name = data['last_name'],
            email=data['email'],
            username=email,
            password=password)
        Profile.objects.create(user=new_user)
        return render(self.request, self.successful_template_name, {'new_user': new_user})


class ProfileUpdateView(View):
    template_name = 'accounts/profile.html'
    
    
    def get(self, request, *args, **kwargs):
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
        return render(request, self.template_name, context={'user_form': user_form,
                                                            'profile_form': profile_form})
    
    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        user = user_record = CustomUser.objects.get_user_by_email(email=email)
        if not user or user.id == request.user.id:
            user_form = UpdateUserForm(instance=request.user, data=request.POST)
            profile_form = UpdateProfileForm(instance=request.user.profile, data=request.POST)
            if user_form.is_valid() and profile_form.is_valid():
                return self.form_valid(user_form, profile_form)
        return self.form_invalid()
                       
    def form_valid(self, user_form, profile_form):
        email = user_form.cleaned_data['email']
        user = user_form.save(commit=False)
        profile = profile_form.save(commit=False)
        user.username = email
        user.save()
        profile.user = user
        profile.save()
        
        messages.success(self.request, 'Profile was updated successfully') 
        return redirect('profile_url')
    
    def form_invalid(self):
        messages.error(self.request, 'User with given email alredy exists') 
        return redirect('profile_url')
        

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Log in {% endblock title %}

{% block content %}

{% if user.is_authenticated %}
<div class="shadow-custom messages alert alert-info col-lg-4 mx-auto text-center">
  You are authenticated as <strong>{{ user.username }}</strong>.
   Would you like to login to a different account?
  <a href="" class="closw">x</a>
</div>
{% endif %}

<div class="card shadow-custom border-0 col-lg-4 mx-auto mb-3">

  <h3 class="py-2 font-weight-bold text-grey text-center">Log in</h3>
  <form action="" method="post">
    {% csrf_token %}
    <div class="input-field">
      {{ form.email }}
      {{ form.email.errors }}
      <label for="email">Email</label>
    </div>
    <div class="input-field">
      {{ form.password }}
      <label for="password">Password</label>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
      Log in
    </button>
  </form>
  <div class="text-center mb-2">
    <a href="{% url 'password_reset' %}" class="text-decoration-none">Forgot password?</a>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Account{% endblock title %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
  <h2 class="font-weight-bold text-grey mt-2">Profile</h2>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="input-field">
          {{ user_form.first_name }}
          <label for="first_name">First name</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ user_form.last_name }}
          <label for="last_name">Last name</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ user_form.email }}
          <label for="email">Email</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ profile_form.phone_number }}
          <label for="phone_number">Phone number</label>
        </div>
      </div>
    </div>
    <hr class="mt-0">
    <div class="row">
      <div class="col-md-6">
        <div class="input-field">
          {{ profile_form.address }}
          <label for="address">Address</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ profile_form.postal_code }}
          <label for="postal_code">Postal code</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ profile_form.city }}
          <label for="city">City</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-field">
          {{ profile_form.country }}
          <label for="country">Country</label>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <button type="submit" class="btn col" data-toggle="tooltip"
       data-placment="top" title="Fill in new details and click 'Update profile'">
       Update profile
      </button>
      <a class="btn col" href="{% url 'password_change' %}">Change password</a>
    </div>
    <hr>
    <h3 class="mb-3">Your orders:</h3>
    <table class="table">
      {% for order in request.user.orders.all%}
        <tr>
          <td>
            <a class="text-decoration-none" href="{{ order.get_absolute_url }}">
              {{ order.id }}
            </a>
          </td>
          <td>{{ order.created|date }}</td>
          <td class="text-green">
            ${{ order.get_total_cost|floatformat:2 }}
          </td>
          <td>
            <a href="{% url 'orders:customer_invoice_pdf' order.id %}" class="text-decoration-none" target="_blank">
              <i class="far fa-file-pdf text-danger"></i>
              Invoice {{ order.id }}
            </a>
          </td>
          <td>{{ order.status }}</td>
        </tr>
        {% empty %}
        <tr>
          No orders yet
        </tr>
      {% endfor %}
    
    </table>
  </form>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3">
  
  <h3 class="py-2 font-weight-bold text-grey text-center">
    Register
  </h3>
  <form action="" method="post">
    <div class="form-group">
      {% csrf_token %}
      <div class="input-field">
        {{ user_form.first_name }}
        {{ user_form.first_name.errors }}
        <label for="first_name">First name</label>
      </div>
      <div class="input-field">
        {{ user_form.last_name }}
        {{ user_form.last_name.errors }}
        <label for="last_name">Last name</label>
      </div>
      <div class="input-field">
        {{ user_form.email }}
        {{ user_form.email.errors }}
        <label for="email">Email</label>
      </div>
      <div class="input-field">
        {{ user_form.password }}
        {{ user_form.password.errors }}
        <label for="password">Password</label>
      </div>
      <div class="input-field">
        {{ user_form.password2 }}
        {{ user_form.password2.errors }}
        <label for="passowrd2">Repeat password</label>
      </div>
      <button class="btn btn-block btn-warning mb-3" type="submit">
        Register
      </button>
    </div>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %}Registration Complete{% endblock %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3 text-center">
  <h3 class="py-2 font-weight-bold text-grey">
    Welcome, {{ new_user.first_name }}
  </h3>
  <hr class="my-0">
  <div class="py-2">
    Your account was successfuly created.
    You can <a href="{% url 'login' %}">log in.</a>
  </div>
</div>
{% endblock content %}