cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail_url'),
    path('add/<int:product_id>/', CartAddProductFormView.as_view(), name='cart_add_url'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove_url')
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    
    # Local apps
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('listings.urls', namespace='listings')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from .views import *

app_name = 'listings'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list_url'),
    path('<slug:category_slug>/', ProductListView.as_view(), name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail')

    ]

templates/inc/_messages.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class="shadow-custom messages alert alert-danger col-lg-4 mx-auto text-center">
        {{ message }}
        <a href="" class="closw">x</a>
      </div>
    {% else %}
      <div class="shadow-custom messages alert alert-{{ message.tags }} col-lg-4 mx-auto text-center">
        {{ message }}
        <a href="" class="closw">x</a>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

templates/inc/_nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top py-1"
    id="main-nav">
    <div class="container">
      <a href="{% url 'listings:product_list_url' %}" class="navbar-brand">
        <h3 class="font-weight-bold">finesauces</h3>
      </a>
      <button class="navbar-toggler" data-toggle="collapse" data-target=#navbarCollapse>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'profile_url' %}" class="nav-link text-white">
                  <i class="fas fa-user"></i> {{ request.user.email }}
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link text-white">
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link text-white">
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link text-white">
                  <i class="fas fa-user-plus"></i>Register
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
          <li class="nav-item">
            <div class="dropdown-custom">
              <a href="{% url 'cart:cart_detail_url' %}" class="nav-link text-white drop-btn">
                <i class="fas fa-shopping-cart"></i>
                $<span id="cart_price">{{ cart_total_price | floatformat:2 }}</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>